version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/html/public:ro
    ports:
      - 8001:80
    environment:
      PHP_HOST: app

  app:
    build: .
    environment:
      - DD_AGENT_HOST=datadog
    #   - APP_DEBUG=true
    #   - APP_KEY=base64:aQ6PdvWEHZKxoqsmZb88vw1Va52KRvCMdqmiV0Z8gGM=
    volumes:
      - .:/var/www/html:cached

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'app'
    ports:
      - 3306

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS="env:${USER}"
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    #XXX: Datadogのログ出力が多すぎるため、ログを破棄
    logging:
      driver: 'none'
